### ISSUE TITLE
资源包无论如何都无法正常加载同时数据包也无法正常的安装

### ISSUE THREAD

**Issue by youjingqiuxi** [SL0ANE/PaintDatapack#1]
![JGQN1ACL3))}($B%M8$DYRU](https://github.com/SL0ANE/PaintDatapack/assets/94136590/e46dcf44-a944-4a9b-a0d4-62a7411755ef)

**Comment by SL0ANE** [comment]
资源包修改了着色器文件，在一些设备上加载不上是可能的。
数据包不起作用就不大清楚了。
如果你能把日志放上来我就能改了。

另外你可以删除assets\minecraft\shaders下的文件来解决这个问题。

我排查了一下可能的问题，降了一下一些着色器的glsl版本，上传了一个新的资源包，你也可以看看现在这个版本能否在你那边正常加载。

**Comment by youjingqiuxi** [comment]
1.0.4版能够正常的加载。数据包和材质包均可以安装
